### ISSUE TITLE
En tant que visiteur ou utilisateur, je veux pouvoir effectuer une recherche globale

### ISSUE THREAD

**Issue by Meknassih** [draden05/LICAsphere_BACK#18]
<a href="https://github.com/Meknassih"><img src="https://avatars0.githubusercontent.com/u/10837495?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Meknassih](https://github.com/Meknassih)**
_Friday Feb 15, 2019 at 14:58 GMT_
_Originally opened as https://github.com/licasphere/LICAsphere_FRONT/issues/18_

----

EPIC #16

**Comment by draden05** [comment]
Closed by e6ada48
