### ISSUE TITLE
Lorsque je recupère le currentUser, je veux obtenir un nouveau "_rev", qui actuellement n'en renvoit pas un bon

### ISSUE THREAD

**Issue by draden05** [draden05/LICAsphere_BACK#23]
Renvoyer un nouveau `_rev` lorsque j'appelle le `currentUser` !
Car quand je récupère le `_rev` de ce dernier, je peux rien faire avec et le serveur me renvoi  `[ExceptionsHandler] Document update conflict.` lorsque je veux update avec ce `_rev` récupérer en dernier (via le currentUser)

**Comment by Meknassih** [comment]
Merci @draden05.
