### ISSUE TITLE
Modifier le type du champ de la biographie de l'utilisateur dans la base de donnée

### ISSUE THREAD

**Issue by draden05** [draden05/LICAsphere_BACK#40]
Changer `var` en `text`/`long text`, car il n'accepte actuellement pas plus de **255** caractères.

**Comment by Meknassih** [comment]
On est pas bien avec 255 caractères? C'est une miniBio pas une autobiographie :p

**Comment by draden05** [comment]
Bof 😂 J'ai pas dis autobiographie non plus mais bon, quand j'essaie de mettre 3 lignes (maxi) c'est pas possible quoi..255 caractères je trouve ça vraiment court 😋
________________________________

**Comment by Meknassih** [comment]
Ouais t'as raison. Ca va alors, on gère ça. 😉 Merci !
