### ISSUE TITLE
Vérifier la validation du numéro de téléphone pour la mise à jour de l'user

### ISSUE THREAD

**Issue by draden05** [draden05/LICAsphere_BACK#50]
Dans **`UserDto `** pour 
```
  @ApiModelProperty()
  phone: string;
```

remplacer par un truc du genre comme **`UserSignupDto`** : 
```
  @ApiModelProperty({ description: 'Country code prefix is mandatory (e.g. +33)' })
  @IsOptional()
  @IsPhoneNumber('ZZ')
  phone: string;
```

**Comment by draden05** [comment]
Franchement tu peux le laisser vu que LICA c'est international ya forcément des gens d’autres pays que le France donc c'est mieux de le laisser :)

**Comment by Meknassih** [comment]
Ok ouais !
