### ISSUE TITLE
En tant qu'utilisateur/visiteur je dois pouvoir recupérer une liste des projets

### ISSUE THREAD

**Issue by haloh9** [draden05/LICAsphere_BACK#54]
La récupération des projets doit se faire en fonction d'un utilisateur (si connecté), sinon il faut juste récupéré tout les projets visibles.

Si l'utilisateur est connecté, en plus des projets visibles, faut récupérer :
- Les projets caché qu'a créé l'utilisateur connecté
- Les projets cachés des projets auxquels il participe

**Comment by Meknassih** [comment]
Les projets cachés sont maintenant visibles lorsque c'est le créateur lui-même qui fait la requête. 
Reste à traiter le deuxième point de cette issue.

**Comment by draden05** [comment]
Ajouter l'attribut optionnel sur le `memberId` et 'creatorId' sur la route `GET /project`

Actuellement : 
![image](https://user-images.githubusercontent.com/19173109/80803357-4f5a9f00-8bb2-11ea-8f2b-58c7d6ab6f78.png)

**Comment by Meknassih** [comment]
> J'ai rajouté 2 subjects à un 2 projets (ceux de l'automobile) lié avec le subject '_transport_' et '_automobile_' je les vois dans `GET /project/:id` mais *pas* dans `GET /project` :wink:
<sub>[View in Slack](https://licasphere.slack.com/archives/DDP8A9NUV/p1588432599006900)</sub>

**Comment by Meknassih** [comment]
> Du coup je te mettrai les 4 dans `membershipsPreview` pour pas confondre et le total de membres dans `membershipsCount`
<sub>[View in Slack](https://licasphere.slack.com/archives/DDP8A9NUV/p1588433295014500)</sub>

**Comment by Meknassih** [comment]
> 
> 
> Ajouter l'attribut optionnel sur le `memberId` et `creatorId` sur la route `GET /project`
> 
> Actuellement :
> ![image](https://user-images.githubusercontent.com/19173109/80803357-4f5a9f00-8bb2-11ea-8f2b-58c7d6ab6f78.png)

Resolved by 89dec57094280b14918c47c485459e58c4db10d7
