### ISSUE TITLE
Rediriger les erreurs 404

### ISSUE THREAD

**Issue by draden05** [draden05/LICAsphere_BACK#59]
Actuellement les erreurs 404 ne sont pas gérées : 
![image](https://user-images.githubusercontent.com/19173109/80707339-18b95180-8aea-11ea-9e1e-e7bc95e70a98.png)

**Comment by Meknassih** [comment]
C'est une feature, c'est tout a fait voulu. Tu veux rediriger vers quoi?

**Comment by draden05** [comment]
Ok, redirection vers la page 404 du Front, soit la route `/#!404` ! :D

**Comment by draden05** [comment]
Closed by 041173a
